name: "EK Bibop"
description: "Action for executing Bibop test recipes"
author: "ESSENTIALKAOS"

branding:
  icon: 'bold'
  color: 'white'

inputs:
  recipe: 
    description: "Path to Bibop recipe"
    required: true

  dry-run:
    description: "Just parse and validate recipe"
    required: false

  format:
    description: "Output format (tap|json|xml)"
    required: false

  working-dir:
    description: "Path to working directory"
    required: false

  path:
    description: "Path to directory with binaries"
    required: false

  tag:
    description: "Command tag"
    required: false

runs:
  using: "composite"
  steps:
    - id: bibop-install
      name: Install Bibop 
      shell: bash
      run: |
        echo "::group::Downloading Bibop…"

        wget -O "$GITHUB_ACTION_PATH/bibop" "https://apps.kaos.st/bibop/latest/linux/x86_64/bibop" 2>&1
        chmod +x "$GITHUB_ACTION_PATH/bibop"

        echo "::endgroup::"

    - id: bibop-set-options
      name: Set Bibop options
      shell: bash
      run : |
        declare -a options

        if [[ -n "${{inputs.dry-run}}" ]] ; then
          options+=("-D")
        fi

        if [[ -n "${{inputs.format}}" ]] ; then
          options+=("-f ${{inputs.format}}")
        fi

        if [[ -n "${{inputs.working-dir}}" ]] ; then
          options+=("-d ${{inputs.working-dir}}")
        fi

        if [[ -n "${{inputs.path}}" ]] ; then
          options+=("-p ${{inputs.path}}")
        fi

        if [[ -t "${{inputs.tag}}" ]] ; then
          options+=("-p ${{inputs.tag}}")
        fi

        echo "::group::Bibop configuration…"
        if [[ ${#options[@]} -eq 0 ]] ; then
          echo "Options: -no-set-"
        else
          echo "Options: ${options[@]}"
        fi
        echo "::endgroup::"

        echo "::set-output name=options::${options[@]}"

    - id: bibop-version-print
      name: Print Bibop version info
      shell: bash
      run: |
        echo "::group::Print Bibop version…"
        $GITHUB_ACTION_PATH/bibop --version
        echo "::endgroup::"

    - id: bibop-check
      name: Run Bibop recipes
      shell: bash
      run: |
        echo "Running Bibop…"
        $GITHUB_ACTION_PATH/bibop ${{steps.bibop-set-options.outputs.options}} ${{inputs.recipe}}
